## Utilização da API fornecida para obtenção de dados de licitações e contratos

In [20]:
import requests
import json

#url = "https://licitacoes.caruaru.pe.gov.br:8082/licitacao/exportar/json"
url_receita = 'https://transparencia.e-publica.net:443/epublica-portal/rest/caruaru/api/v1/receita/'
response = requests.get(url_receita)


if response.status_code == 200:
    data = response.json()
    output_file = "licitacoes.json"

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
    
    print(f"Arquivo salvo como {output_file}")
else:
    print("Erro na requisição. Status Code: {response.status_code}")

Erro na requisição. Status Code: {response.status_code}

In [2]:
import os

In [11]:
path = os.getcwd()
file = 'licitacoes.json'
file_path = os.path.join(path, file)

'/home/tiago/Workspace/projetos/mutuca/nbs/notebooks/prefeitura_municipal/licitacoes.json'

In [14]:

with open(file_path, "r") as f:
    data = json.load(f)

In [15]:
data

[{'numero': '090059/2024',
  'processo': '0083/2024',
  'dataDeRealizacao': '01/10/2024',
  'dataDePublicacao': '17/09/2024',
  'modalidade': 'Pregão eletrônico',
  'orgao': 'Secretaria de Saúde',
  'fase': 'Aberta',
  'tipoObjeto': 'Compras e serviços',
  'objeto': 'Futura Locação de Ônibus, Visando Atender Ao Programa Tratamento Fora Do Domicílio (TFD) - Incluído Seguro Total Contra Acidentes, Combustível, Manutenção e Mão De Obra Especializada, Além De Equipamento De Acessibilidade Para Embarque - para transportar usuários do Sistema Único de Saúde...',
  'valorEstimado': 'R$ 3.019.948,80',
  'valorContratado': '',
  'vencedor': None,
  'comissao': 'CPL G'},
 {'numero': '090048/2024',
  'processo': '0022/2024',
  'dataDeRealizacao': '20/09/2024',
  'dataDePublicacao': '20/09/2024',
  'modalidade': 'Pregão eletrônico',
  'orgao': 'Secretaria de Educação',
  'fase': 'Aberta',
  'tipoObjeto': 'Compras e serviços',
  'objeto': 'Registro de Preços para eventual e futura Aquisição de Pneus Novos, a fim de atender às necessidades da Secretaria de Educação e Esportes- SEDUC.',
  'valorEstimado': 'R$ 185.939,20',
  'valorContratado': '',
  'vencedor': None,
  'comissao': 'CPL Educação'},
 {'numero': '090049/2024',
  'processo': '0023/2023',
  'dataDeRealizacao': '26/09/2024',
  'dataDePublicacao': '11/09/2024',
  'modalidade': 'Pregão eletrônico',
  'orgao': 'Secretaria de Educação',
  'fase': 'Aberta',
  'tipoObjeto': 'Compras e serviços',
  'objeto': 'Contratação do serviço de transporte escolar de alunos, adaptado e especializado do tipo porta-a-porta para atender os discentes com alto grau de deficiência física e alto grau de dificuldade de locomoção, incluindo veículos, motoristas, combustível, manutenção e gerenciamento.',
  'valorEstimado': 'R$ 1.423.726,92',
  'valorContratado': '',
  'vencedor': None,
  'comissao': 'UC- EDUCAÇÃO'},
 {'numero': '090028/2024',
  'processo': '0010/2024',
  'dataDeRealizacao': '13/06/2024',
  'dataDePublicacao': '03/06/2024',
  'modalidade': 'Pregão eletrônico',
  'orgao': 'Secretaria de Educação',
  'fase': 'Aberta',
  'tipoObjeto': 'Compras e serviços',
  'objeto': 'REGISTRO DE PREÇOS VISANDO A AQUISIÇÃO DE EQUIPAMENTOS E MATERIAIS PARA ATIVIDADES ESPORTIVAS, visando suprir as necessidades da Gerência de Esportes, junto à Secretaria de Educação e Esportes do Município de Caruaru.',
  'valorEstimado': 'R$ 1.732.171,59',
  'valorContratado': '',
  'vencedor': None,
  'comissao': 'UC- EDUCAÇÃO'},
 {'numero': '090018/2024',
  'processo': '0023/2024',
  'dataDeRealizacao': '23/08/2024',
  'dataDePublicacao': '09/08/2024',
  'modalidade': 'Concorrência',
  'orgao': 'Secretaria de Urbanismo e Obras',
  'fase': 'Aberta',
  'tipoObjeto': 'Obras e serviços de engenharia',
  'objeto': 'Recapeamento e sinalização em diversas vias no bairro do Salgado, Caruaru/PE.',
  'valorEstimado': 'R$ 977.592,10',
  'valorContratado': '',
  'vencedor': None,
  'comissao': 'UC-O'},
 {'numero': '090009/2024',
  'processo': '0013/2024',
  'dataDeRealizacao': '12/07/2024',
  'dataDePublicacao': '02/07/2024',
  'modalidade': 'Pregão eletrônico',
  'orgao': 'Secretaria de Saúde',
  'fase': 'Homologada',
  'tipoObjeto': 'Compras e serviços',
  'objeto': 'Contratação de empresa especializada no ramo de Seguros de Veículos. Sendo 25 (vinte e cinco) tipo ambulância e 01 (um) veículo tipo van para transporte sanitário, a serviço da Secretaria\nMunicipal de Saúde do Município de Caruaru-PE, durante o período de 12 (doze) meses.',
  'valorEstimado': 'R$ 131.544,09',
  'valorContratado': 'R$ 80.000,00',
  'vencedor': None,
  'comissao': 'UC-SMS'},
 {'numero': '090039/2024',
  'processo': '0017/2024',
  'dataDeRealizacao': '10/07/2024',
  'dataDePublicacao': '09/07/2024',
  'modalidade': 'Pregão eletrônico',
  'orgao': 'Secretaria de Administração',
  'fase': 'Homologada',
  'tipoObjeto': 'Compras e serviços',
  'objeto': 'Constitui objeto do presente Pregão Eletrônico o Registro de Preços para eventual e futuro fornecimento de PAPEL SULFITE A4, a fim de atender às necessidades administrativas dos órgãos e entidades da Administração Direta e Indireta da Prefeitura Municipal de Caruaru.',
  'valorEstimado': 'R$ 839.678,59',
  'valorContratado': '',
  'vencedor': None,
  'comissao': 'UC- EDUCAÇÃO'},
 {'numero': '090008/2024',
  'processo': '0011/2024',
  'dataDeRealizacao': '04/06/2024',
  'dataDePublicacao': '17/05/2024',
  'modalidade': 'Concorrência',
  'orgao': 'Secretaria de Urbanismo e Obras',
  'fase': 'Homologada',
  'tipoObjeto': 'Obras e serviços de engenharia',
  'objeto': 'Pavimentação, drenagem e sinalização no Beco de Lajes, localizado no Povoado de Lajes, Ruas no Povoado de Jacaré Grande e Acesso ao Cemitério de Peladas Zona Rural do município de Caruaru/PE.',
  'valorEstimado': 'R$ 2.339.856,91',
  'valorContratado': '',
  'vencedor': None,
  'comissao': 'UC-O'},
 {'numero': '090029/2024',
  'processo': '0060/2024',
  'dataDeRealizacao': '06/06/2024',
  'dataDePublicacao': '22/05/2024',
  'modalidade': 'Pregão eletrônico',
  'orgao': 'Secretaria de Administração',
  'fase': 'Homologada',
  'tipoObjeto': 'Compras e serviços',
  'objeto': 'Contratação de empresa visando a aquisição de água potável mineral natural, sem gás, envasada mecanicamente em garrafão de Polietileno Tereftalato (PET), livre do composto bisfenol-A (BPA) retornável com capacidade 20 litros, em regime de comodato; garrafas PET de 500 ml, Copos descartáveis de 200..',
  'valorEstimado': 'R$ 3.218.206,46',
  'valorContratado': '',
  'vencedor': None,
  'comissao': 'UC- G'},
 {'numero': '090018/2024',
  'processo': '0020/2024',
  'dataDeRealizacao': '14/05/2024',
  'dataDePublicacao': '29/04/2024',
  'modalidade': 'Pregão eletrônico',
  'orgao': 'Secretaria de Administração',
  'fase': 'Homologada',
  'tipoObjeto': 'Compras e serviços',
  'objeto': 'Locação de Micro-Ônibus, Ônibus e Veículos Tipo Van, Visando Atender Ao Programa Tratamento Fora Do Domicílio (TFD) - Incluído Seguro Total Contra Acidentes, Combustível, Manutenção e Mão De Obra Especializada, Além De Equipamento De Acessibilidade .',
  'valorEstimado': 'R$ 6.948.538,08',
  'valorContratado': '',
  'vencedor': None,
  'comissao': 'UC- G'},
 {'numero': '090058/2024',
  'processo': '0034/2024',
  'dataDeRealizacao': '02/10/2024',
  'dataDePublicacao': '18/09/2024',
  'modalidade': 'Pregão eletrônico',
  'orgao': 'CARUARUPREV',
  'fase': 'Aberta',
  'tipoObjeto': 'Compras e serviços',
  'objeto': 'Constitui objeto deste Edital a contratação de empresa especializada para realização de Censo Previdenciário e armazenamento dos dados cadastrais, funcionais e financeiros dos servidores efetivos ativos, inativos, \npensionistas e dependentes que tem sua vinculação previdenciária junto ao Instituto ',
  'valorEstimado': 'R$ 318.800,64',
  'valorContratado': '',
  'vencedor': None,
  'comissao': 'UC-P'},
 {'numero': '090009/2024',
  'processo': '0014/2024',
  'dataDeRealizacao': '17/06/2024',
  'dataDePublicacao': '29/05/2024',
  'modalidade': 'Concorrência',
  'orgao': 'Secretaria de Urbanismo e Obras',
  'fase': 'Homologada',
  'tipoObjeto': 'Obras e serviços de engenharia',
  'objeto': 'Execução da reforma e requalificação da edificaçaõ para instalação de velório público, localizado no Povoado de Itaúna, município de Caruaru-PE.',
  'valorEstimado': 'R$ 161.973,18',
  'valorContratado': '',
  'vencedor': None,
  'comissao': 'UC-O'},
 {'numero': '090019/2024',
  'processo': '0024/2024',
  'dataDeRealizacao': '10/09/2024',
  'dataDePublicacao': '27/08/2024',
  'modalidade': 'Concorrência',
  'orgao': 'Secretaria de Urbanismo e Obras',
  'fase': 'Homologada',
  'tipoObjeto': 'Obras e serviços de engenharia',
  'objeto': 'Pavimentação em paralelepípedos, drenagem e sinalização de diversas vias no Bairro Deputado José Antônio Liberato, Caruaru/PE.',
  'valorEstimado': 'R$ 4.474.712,13',
  'valorContratado': '',
  'vencedor': None,
  'comissao': 'UC-O'},
 {'numero': '090019/2024',
  'processo': '0014/2024',
  'dataDeRealizacao': '24/05/2024',
  'dataDePublicacao': '27/05/2024',
  'modalidade': 'Pregão eletrônico',
  'orgao': 'Autarquia Municipal de Defesa Social, Trânsito e Transporte',
  'fase': 'Homologada',
  'tipoObjeto': 'Compras e serviços',
  'objeto': 'AQUISIÇÃO DE TENDA INFLÁVEL, MESAS E CADEIRAS, em atendimento as necessidades da Autarquia de Mobilidade, Trânsito e Transportes de Caruaru – AMTTC\n',
  'valorEstimado': 'R$ 5.983,69',
  'valorContratado': 'R$ 4.953,00',
  'vencedor': None,
  'comissao': 'UC-P'},
 {'numero': '090009/2024',
  'processo': '0005/2024',
  'dataDeRealizacao': '11/04/2024',
  'dataDePublicacao': '01/04/2024',
  'modalidade': 'Pregão eletrônico',
  'orgao': 'Secretaria de Administração',
  'fase': 'Homologada',
  'tipoObjeto': 'Compras e serviços',
  'objeto': 'Contratação de empresa(s) para fornecimento de materiais elétricos diversos, destinados a Gerência de Iluminação da SESP a fim de atender as necessidades dos eventos públicos realizados no Município de Caruaru .',
  'valorEstimado': 'R$ 1.525.238,22',
  'valorContratado': '',
  'vencedor': None,
  'comissao': 'UC- G'}]

In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame(data)

In [18]:
df.head()

,numero,processo,dataDeRealizacao,dataDePublicacao,modalidade,orgao,fase,tipoObjeto,objeto,valorEstimado,valorContratado,vencedor,comissao
0,090059/2024,0083/2024,01/10/2024,17/09/2024,Pregão eletrônico,Secretaria de Saúde,Aberta,Compras e serviços,"Futura Locação de Ônibus, Visando Atender Ao P...","R$ 3.019.948,80",,None,CPL G
1,090048/2024,0022/2024,20/09/2024,20/09/2024,Pregão eletrônico,Secretaria de Educação,Aberta,Compras e serviços,Registro de Preços para eventual e futura Aqui...,"R$ 185.939,20",,None,CPL Educação
2,090049/2024,0023/2023,26/09/2024,11/09/2024,Pregão eletrônico,Secretaria de Educação,Aberta,Compras e serviços,Contratação do serviço de transporte escolar d...,"R$ 1.423.726,92",,None,UC- EDUCAÇÃO
3,090028/2024,0010/2024,13/06/2024,03/06/2024,Pregão eletrônico,Secretaria de Educação,Aberta,Compras e serviços,REGISTRO DE PREÇOS VISANDO A AQUISIÇÃO DE EQUI...,"R$ 1.732.171,59",,None,UC- EDUCAÇÃO
4,090018/2024,0023/2024,23/08/2024,09/08/2024,Concorrência,Secretaria de Urbanismo e Obras,Aberta,Obras e serviços de engenharia,Recapeamento e sinalização em diversas vias no...,"R$ 977.592,10",,None,UC-O

In [19]:
df.count()

numero              15
processo            15
dataDeRealizacao    15
dataDePublicacao    15
modalidade          15
orgao               15
fase                15
tipoObjeto          15
objeto              15
valorEstimado       15
valorContratado     15
vencedor             0
comissao            15
dtype: int64

## Gerando o dicionário de códigos das unidades do governo

Será útil termo à mão os códigos referentes a cada unidade gestora. A página da api trás uma tabela identificando cada unidade por seu código. Para obter essas informações eu busquei o arquivo que retorna estas informações e fiz uma cópia simples do arquivo para o ambiente local. 

![cod_unidades]('/home/tiago/Workspace/projetos/mutuca/docs/assets/cityhall_assets/cod_unidade_gestora_response.png')

In [28]:
base_path = os.getcwd()
file = 'dicionario.json'
dicionario_path = os.path.join(base_path, file)

with open(dicionario_path, 'r') as f:
    dicionario = json.load(f)

dicionario.keys()

dict_keys(['actions', 'pojo', 'fields', 'title', 'subtitle', 'showViewAction', 'useDirty', 'permissionMap', 'infoLabel', 'extensao', 'useFieldsIndicators', 'validateOnExit', 'forceInfoModeWhenData'])

In [36]:
json_data = dicionario.get('pojo')

unidades = pojo.get('unidades')

unidades_list = []
for unidade in unidades:
    unidades_dicionario = {
        unidade['codigo']: unidade['denominacaoPara'].replace('para', '').strip(),
    }
    unidades_list.append(unidades_dicionario)


unidades_list

[{2: 'Prefeitura Municipal de Caruaru'},
 {3: 'Consórcio dos Municípios Pernambucanos - COMUPE'},
 {4: 'CONIAPE - Consórcio Público Intermunicipal do Agreste Pernambucano e Fronteiras'},
 {3012: 'CARUARUPREV - FUNDO PREVIDENCIÁRIO'},
 {43002: 'Câmara Municipal de Vereadores de Caruaru'},
 {43006: 'Fundação de Cultura de Caruaru'},
 {43008: 'Fundo Municipal de Saúde de Caruaru'},
 {43009: 'Fundo Municipal da Criança e Adolescente de Caruaru - FUNDECA'},
 {43010: 'Fundo Municipal de Assistência Social de Caruaru'},
 {43012: 'CARUARUPREV'},
 {43014: 'Fundo Municipal dos Direitos da Pessoa Idosa de Caruaru'},
 {43018: 'Central de Abastecimento de Caruaru - CEACA'},
 {43019: 'Autarquia de Urbanização e Meio Ambiente de Caruaru'},
 {43020: 'Autarquia de Mobilidade, Trânsito e Transporte de Caruaru - AMTTC'}]

In [37]:
import csv

In [41]:
with open('codigo_unidades.csv', mode='w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)

    writer.writerow(['cod_unidade_gestora', 'nome_unidade_gestora'])

    for unidade_dict in unidades_list:
        for cod_unidade, nome_unidade in unidade_dict.items():
            writer.writerow([cod_unidade, nome_unidade])
    print("Dicionário de Unidades Gestoras exportadas com sucesso para 'codigo_unidades.csv'")

Dicionário de Unidades Gestoras exportadas com sucesso para 'codigo_unidades.csv'

## Receitas

In [15]:
import os
import requests
import json
import pandas as pd

In [8]:
periodo_inicial = '01/2024'
periodo_final = '10/2024'
codigo_unidade = '2'

In [9]:
url = f'https://transparencia.e-publica.net/epublica-portal/rest/caruaru/api/v1/receita?periodo_inicial={periodo_inicial}&periodo_final={periodo_final}&codigo_unidade={codigo_unidade}'

In [10]:
resp = requests.get(url)

In [11]:
resp

In [12]:
data = resp.json()

In [13]:
df = pd.DataFrame(data)

In [14]:
df.head()

,informacao,ultimaAtualizacao,totalRegistros,registros
0,Receita,11/10/2024,97,"{'registro': {'receita': {'codigo': 224, 'tipo..."
1,Receita,11/10/2024,97,"{'registro': {'receita': {'codigo': 258, 'tipo..."
2,Receita,11/10/2024,97,"{'registro': {'receita': {'codigo': 54, 'tipoR..."
3,Receita,11/10/2024,97,"{'registro': {'receita': {'codigo': 53, 'tipoR..."
4,Receita,11/10/2024,97,"{'registro': {'receita': {'codigo': 51, 'tipoR..."